### ISSUE TITLE
Good favicon format logo  

### ISSUE THREAD

**Issue by suvanbalu** [suvanbalu/caterbid#3]
Want a good logo for the browser tab logo of our site, 

<img width="210" alt="image" src="https://user-images.githubusercontent.com/46626983/212980108-f0277016-4490-4c25-a693-b373e50ddc72.png">

<img width="93" alt="image" src="https://user-images.githubusercontent.com/46626983/212980425-aaa500be-f3db-46a1-8cb6-dede25b8893b.png">
_(current logo)_     

    
Comment on the issues with links to the images (preferably favicon formatted pictures)

**Comment by shxvani** [comment]
The CaterBid Logo?

**Comment by shxvani** [comment]
https://icons8.com/icon/9mi19yupXadC/buffet
https://icons8.com/icon/BI2FEPylFnA2/catering
https://icons8.com/icon/smYNLa8eV8ii/waiter
https://icons8.com/icon/thHlz8ltCREK/restaurant-review
https://icons8.com/icon/rd1LC8z4oxVG/restaurant-review
